using Bogus;
using CustomerCatalog.Core.Models;
using Dapper;
using Microsoft.Data.SqlClient;
using Serilog;

namespace CustomerCatalog.Core.Data;

/// <summary>
/// Ensures the database and table exist and – when the table is empty – fills it
/// with test data generated by Bogus.
/// </summary>
public sealed class DatabaseInitializer
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly int _seedCount;

    public DatabaseInitializer(IDbConnectionFactory connectionFactory, int seedCount = 50)
    {
        _connectionFactory = connectionFactory ?? throw new ArgumentNullException(nameof(connectionFactory));
        _seedCount = seedCount;
    }

    /// <summary>
    /// Creates the database (if missing), the Customers table (if missing) and seeds
    /// data when the table is empty.
    /// </summary>
    public void EnsureCreatedAndSeeded()
    {
        EnsureDatabaseExists();
        EnsureTableExists();
        SeedIfEmpty();
    }

    private void EnsureDatabaseExists()
    {
        var builder = new SqlConnectionStringBuilder(_connectionFactory.ConnectionString);
        var databaseName = builder.InitialCatalog;
        if (string.IsNullOrWhiteSpace(databaseName))
            throw new InvalidOperationException("Connection string does not specify a database (Initial Catalog / Database).");

        // Connect to 'master' so the target database can be created.
        builder.InitialCatalog = "master";
        using var connection = new SqlConnection(builder.ConnectionString);
        connection.Open();

        // The database name comes from configuration; QUOTENAME guards against injection.
        const string sql = """
            IF DB_ID(@dbName) IS NULL
            BEGIN
                DECLARE @cmd nvarchar(max) = N'CREATE DATABASE ' + QUOTENAME(@dbName);
                EXEC(@cmd);
            END
            """;
        connection.Execute(sql, new { dbName = databaseName });
        Log.Information("Database {Database} is ready.", databaseName);
    }

    private void EnsureTableExists()
    {
        using var connection = _connectionFactory.CreateOpenConnection();
        connection.Execute(CustomerSchema.CreateTableIfNotExistsSql);
    }

    private void SeedIfEmpty()
    {
        using var connection = _connectionFactory.CreateOpenConnection();
        var count = connection.ExecuteScalar<int>("SELECT COUNT(*) FROM Customers;");
        if (count > 0)
            return;

        var customers = GenerateFakeCustomers(_seedCount);
        const string insert = """
            INSERT INTO Customers (Name, Nip, Street, PostalCode, City, Phone, Email, CreatedAt)
            VALUES (@Name, @Nip, @Street, @PostalCode, @City, @Phone, @Email, @CreatedAt);
            """;

        var rows = customers.Select(c => new
        {
            c.Name,
            Nip = c.Nip.Value,
            Street = c.Address.Street,
            PostalCode = c.Address.PostalCode,
            City = c.Address.City,
            c.Phone,
            Email = c.Email.Value,
            c.CreatedAt
        });
        connection.Execute(insert, rows);
        Log.Information("Seeded {Count} customers with test data (Bogus).", customers.Count);
    }

    /// <summary>
    /// Generates a list of random customers. Public so it can be reused in tests.
    /// Uses a fixed seed for reproducibility.
    /// </summary>
    public static IReadOnlyList<Customer> GenerateFakeCustomers(int count)
    {
        Randomizer.Seed = new Random(12345);

        var faker = new Faker<Customer>("pl")
            .RuleFor(c => c.Name, f => f.Company.CompanyName())
            .RuleFor(c => c.Nip, f => GenerateValidNip(f))
            .RuleFor(c => c.Address, f => Address.Parse(
                f.Address.StreetAddress(),
                GeneratePolishPostalCode(f),
                f.Address.City()))
            .RuleFor(c => c.Phone, f => f.Phone.PhoneNumber("### ### ###"))
            .RuleFor(c => c.Email, f => Email.Parse(f.Internet.Email(provider: "example.com")))
            .RuleFor(c => c.CreatedAt, f => f.Date.Past(2));

        return faker.Generate(count);
    }

    /// <summary>Generates a valid NIP (9 random digits + a computed check digit).</summary>
    private static Nip GenerateValidNip(Faker f)
    {
        int[] weights = { 6, 5, 7, 2, 3, 4, 5, 6, 7 };
        while (true)
        {
            var digits = new int[10];
            var sum = 0;
            for (var i = 0; i < 9; i++)
            {
                digits[i] = f.Random.Int(0, 9);
                sum += digits[i] * weights[i];
            }

            var check = sum % 11;
            if (check == 10)
                continue; // Invalid check digit – draw again.

            digits[9] = check;
            if (Nip.TryParse(string.Concat(digits), out var nip))
                return nip!;
        }
    }

    /// <summary>
    /// Builds a Polish-format postal code (NN-NNN) directly, rather than relying on Bogus'
    /// locale data to happen to match — keeps seeding independent of that data's exact shape.
    /// </summary>
    private static string GeneratePolishPostalCode(Faker f) =>
        $"{f.Random.Int(0, 99):00}-{f.Random.Int(0, 999):000}";
}
